batch_size: 8
num_workers: 1
data_path: data/raw/Subtask_1_trial.json
tokenize_data_path: data/tokenized/trial.pkl
checkpoint: nlp-09-01-2024-comparison/keagizyf/checkpoints/model-epoch=02-val_loss=2.06.ckpt
out_file: out.json
model_name: bert-base-uncased
training_strategy:
model:
  hidden_dropout_prob: 0.6
weight_decay: 0.1
lr: 0
label_smoothing: 0
