batch_size: 4
num_epochs: 5
val_size: 0.15
test_size: 0.15
lr: 2e-5
num_workers: 6
label_smoothing: 0.1
tokenize_data_path: data/tokenized/train.pkl
model_name: bert-base-cased
training_strategy: heads
